version: '3'

tasks:
  install_brew:
    desc: Install brew
    cmds:
      - |
        if ! [ -x "$(command -v brew)" ]; then
          echo "Installing brew"
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        fi
    silent: true

  install:
    desc: Install tools
    deps:
      - task: install_brew
    cmds:
      - brew install zsh-autosuggestions
    silent: true
